# WorksBien Dev Dashboard app: Exact Search Guard
client_id = "4ed164c8367bd874ae7a28cfdc51b472"
name = "Exact Search Guard"
application_url = "https://exact-search-guard.worksbienstudios.com"
embedded = true

[access_scopes]
scopes = "read_products,write_app_proxy"

[auth]
redirect_urls = ["https://exact-search-guard.worksbienstudios.com/auth/callback"]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = ["products/create", "products/update", "products/delete"]
  uri = "/webhooks/products"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = ["bulk_operations/finish"]
  uri = "/webhooks/bulk-operations"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks/compliance"

[app_proxy]
url = "/proxy/search-guard"
prefix = "apps"
subpath = "exact-search"
